#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Sun Oct 20 04:15:24 2013
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU | wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Start"))
        self.spin_ctrl_1 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "", min=0, max=100)
        self.static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        self.label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Stop"))
        self.spin_ctrl_2 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "50", min=0, max=100)
        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.SUNKEN_BORDER)
        self.sizer_5_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, _("Left"))
        self.label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Start"))
        self.spin_ctrl_3 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "", min=0, max=100)
        self.static_line_2 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        self.label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Stop"))
        self.spin_ctrl_4 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "100", min=0, max=100)
        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.SUNKEN_BORDER)
        self.sizer_6_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, _("Right"))
        self.button_1 = wx.ToggleButton(self.panel_1, wx.ID_ANY, _("Leds off"))
        self.button_2 = wx.ToggleButton(self.panel_1, wx.ID_ANY, _("Manual Control"))
        self.sizer_12_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, _("Control"))
        self.button_5 = wx.Button(self.panel_1, wx.ID_ANY, _("Set All"))
        self.button_3 = wx.Button(self.panel_1, wx.ID_ANY, _("Set Left"))
        self.button_4 = wx.Button(self.panel_1, wx.ID_ANY, _("Set Right"))
        self.sizer_13_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, _("Manual Control"))
        self.sizer_2_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, _("Ambilight Settings"))
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.menuHide = wx.MenuItem(wxglade_tmp_menu, wx.ID_ANY, _("&Hide"), _("Hide application"), wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.menuHide)
        wxglade_tmp_menu.AppendSeparator()
        self.menuQuit = wx.MenuItem(wxglade_tmp_menu, wx.ID_ANY, _("&Quit"), _("Quit application"), wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.menuQuit)
        self.frame_1_menubar.Append(wxglade_tmp_menu, _("&File"))
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOGGLEBUTTON, self.ledPower, self.button_1)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.AutoMode, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.setAll, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.setLeft, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.setRight, self.button_4)
        self.Bind(wx.EVT_MENU, self.Hide, self.menuHide)
        self.Bind(wx.EVT_MENU, self.Quit, self.menuQuit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("ZeroLight"))
        self.SetSize((400, 400))
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = [_("frame_1_statusbar")]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_2_staticbox.Lower()
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_13_staticbox.Lower()
        sizer_13 = wx.StaticBoxSizer(self.sizer_13_staticbox, wx.VERTICAL)
        self.sizer_12_staticbox.Lower()
        sizer_12 = wx.StaticBoxSizer(self.sizer_12_staticbox, wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_6_staticbox.Lower()
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_5_staticbox.Lower()
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(self.label_1, 0, 0, 0)
        sizer_8.Add(self.spin_ctrl_1, 0, 0, 0)
        sizer_8.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_8.Add(self.label_2, 0, 0, 0)
        sizer_8.Add(self.spin_ctrl_2, 0, 0, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_7.Add(self.panel_2, 1, wx.EXPAND, 0)
        sizer_5.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_10.Add(self.label_3, 0, 0, 0)
        sizer_10.Add(self.spin_ctrl_3, 0, 0, 0)
        sizer_10.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_10.Add(self.label_4, 0, 0, 0)
        sizer_10.Add(self.spin_ctrl_4, 0, 0, 0)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_9.Add(self.panel_3, 1, wx.EXPAND, 0)
        sizer_6.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_12.Add(self.button_1, 0, 0, 0)
        sizer_12.Add(self.button_2, 0, 0, 0)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_13.Add(self.button_5, 0, 0, 0)
        sizer_13.Add(self.button_3, 0, 0, 0)
        sizer_13.Add(self.button_4, 0, 0, 0)
        sizer_11.Add(sizer_13, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_11, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, 0, 10)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def ledPower(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'ledPower' not implemented!"
        event.Skip()

    def AutoMode(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'AutoMode' not implemented!"
        event.Skip()

    def setAll(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'setAll' not implemented!"
        event.Skip()

    def setLeft(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'setLeft' not implemented!"
        event.Skip()

    def setRight(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'setRight' not implemented!"
        event.Skip()

    def Hide(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'Hide' not implemented!"
        event.Skip()

    def Quit(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'Quit' not implemented!"
        event.Skip()

# end of class MyFrame
class ZeroLight(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class ZeroLight

if __name__ == "__main__":
    gettext.install("ZeroLight") # replace with the appropriate catalog name

    ZeroLight = ZeroLight(0)
    ZeroLight.MainLoop()